config/routes.rb
Rails.application.routes.draw do
  resources :bills do
    collection do
      get 'load_json'
      post 'save_json'
      get 'load_collection_json'
      post 'save_collection_json'
    end
    resources :collections
  end

  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :collections
  validates_uniqueness_of :reference

  def total_collection
  	Bill.joins(:collections).where("bills.id=#{id}").sum("collections.amount")
  end

  def balance_due
    amount.to_i-total_collection
  end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :bill
  validate :allowed_reference, :allowed_amount
  validates_presence_of :amount, :collection_date, :bill_id

  def allowed_reference
  	unless reference == bill.reference
  	  errors.add(:reference, "is not matching with the bill's reference")
  	end
  end

  def allowed_amount
  	unless amount.to_i <=  bill.balance_due
  	  errors.add(:amount, "is greater than the bill's balance due")
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    if filter_params.present? && filter_params[:filter] == "pending"
      @bills = Bill.joins(:collections).having("(bills.amount-SUM(collections.amount)) = 0").group("bills.id")
    elsif filter_params.present? && filter_params[:filter] == "collected"
      @bills = Bill.joins(:collections).having("(bills.amount-SUM(collections.amount)) != 0").group("bills.id")
    else
      @bills = Bill.all
    end
  end
  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  def load_json
  end

  def save_json
    @json = JSON.parse(json_params[:attachment].read)
    failed_objects_array = []
    @json.each do |json|
      b = Bill.create(json)
      unless b.persisted?
       failed_objects_array << b.errors.full_messages
      end
    end
    redirect_to bills_path, notice: failed_objects_array.join(",")
  end

  def load_collection_json
  end

  def save_collection_json
    @json = JSON.parse(json_params[:attachment].read)
    failed_objects_array = []
    @json.each do |json|
      b = Bill.where(reference: json["reference"])
      unless b.empty?
        c = b[0].collections.create(json)
        unless c.persisted?
         failed_objects_array << c.errors.full_messages
        end
      else
        failed_objects_array << "There is no bill with reference #{json["reference"]}"
      end
    end
    redirect_to bills_path, notice: failed_objects_array.join(",")
  end
  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bills_path, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:invoice_date, :customer_name, :brand_manager, :narration, :amount, :reference)
    end

    def filter_params
      params.permit(:filter)
    end

    def json_params
      params.permit(:attachment)
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def new
    @bill = Bill.find(params[:bill_id])
    @collection = @bill.collections.new
  end

  def create
  	@collection = Collection.new(collection_params)
    respond_to do |format|
      if @collection.save
        format.html { redirect_to bills_path, notice: 'collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        @bill = Bill.find(params[:bill_id])
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end



  private

  def collection_params
    params.require(:collection).permit(:reference, :bill_id, :amount, :collection_date)
  end
  def json_params
    params.permit(:attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :invoice_date %><br>
    <%= f.date_select :invoice_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :brand_manager %><br>
    <%= f.text_field :brand_manager, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :narration %><br>
    <%= f.text_field :narration, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :amount %><br>
    <%= f.number_field :amount, min: 0, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :reference %><br>
    <%= f.text_field :reference, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-raised btn-info"%>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h3>Invoice List</h3>
<br>
<div class="col-md-2">
  <%= link_to 'Add a new bill', new_bill_path, class: "btn btn-raised btn-primary" %>
</div>
<div class="col-md-3">
  <%= link_to 'Add a new bill with Json', load_json_bills_path, class: "btn btn-raised btn-primary" %>
</div>
<div class="col-md-3">
  <%= link_to 'Add a new collection with Json', load_collection_json_bills_path, class: "btn btn-raised btn-primary" %>
</div>
<div class="col-md-2">
  <%= link_to 'Show Pending bills', bills_path(filter: "pending"), class: "btn btn-raised btn-primary" %>
</div>
<div class="col-md-2">
  <%= link_to 'Show Collected bills', bills_path(filter: "collected"), class: "btn btn-raised btn-primary" %>
</div>
<br><br>
<table>
  <thead>
    <tr>
      <th>Reference</th>
      <th>Invoice date</th>
      <th>Customer name</th>
      <th>Brand manager</th>
      <th>Narration</th>
      <th>Amount</th>
      <th>Total Collection</th>
      <th>Balance Due</th>
      <th>Button to add a collection</th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= link_to "#{bill.reference}",bill %></td>
        <td><%= bill.invoice_date %></td>
        <td><%= bill.customer_name %></td>
        <td><%= bill.brand_manager %></td>
        <td><%= bill.narration %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.total_collection %></td>
        <td><%= bill.balance_due %></td>
        <td><%= link_to "Add Collection",new_bill_collection_path(bill,reference: bill.reference ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bills/load_collection_json.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>New Collection</h1>
  <%= form_tag(save_collection_json_bills_path, method: :post, multipart: true) do %>
    <%= file_field_tag 'attachment' %><br>
    <%= submit_tag "Create", class: "btn btn-raised btn-info" %> 
  <% end -%>
</div>

app/views/bills/load_json.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>New Bill</h1>
  <%= form_tag(save_json_bills_path, method: :post, multipart: true) do %>
    <%= file_field_tag 'attachment' %><br>
    <%= submit_tag "Create", class: "btn btn-raised btn-info" %> 
  <% end -%>
</div>

app/views/bills/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1 style="text-align: center">New Bill</h1>
  <%= render 'form' %>
  <br><%= link_to 'Back', bills_path,class: "btn btn-raised btn-info" %>
</div>

app/views/bills/show.html.erb
<h3>Invoice View</h3>
  <h4><%= @bill.reference %></h4>
  <h4><%= @bill.customer_name %></h4>
  <h4><%= @bill.brand_manager %></h4>
  <h4><%= @bill.narration %></h4>
  <br>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Event</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @bill.invoice_date %></td>
        <td>New Invoice</td>
        <td><%= @bill.amount %></td>
      </tr>
      <% @bill.collections.each do |collection| %>
        <tr>
          <td><%= collection.collection_date %></td>
          <td>Collection</td>
          <td><%= collection.amount %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>

app/views/collections/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2 style="text-align: center">Add a new Collection</h2>

  <%= form_for [@bill,@collection] do |f| %>
    <% if @collection.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this bill from being saved:</h2>

        <ul>
        <% @collection.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :amount %><br>
      <%= f.number_field :amount, min: 0, class: "form-control" %> 
    </div>
    <div class="form-group">
      <%= f.hidden_field(:reference, :value => params[:reference]) %>
    </div>
    <div class="form-group">
      <%= f.label :collection_date %><br>
      <%= f.date_select :collection_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.hidden_field(:bill_id, :value => params[:bill_id]) %>
    </div>
      <%= f.submit class: "btn btn-raised btn-info" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Actionboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <br><%= flash_messages %>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>